[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Notes:
# - The Next.js plugin handles all routing (including dynamic routes & SSR) so no manual catch-all redirect is needed.
# - Publish directory should remain .next for the plugin to process server output.
