[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Enable Next.js caching for faster subsequent builds
[functions]
  node_bundler = "esbuild"

# Redirect all requests to Next.js handler (optional if using Next Runtime automatically)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
